# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = cmake

# The command to remove a file.
RM = cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR := $(shell readlink -f .)

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR := $(shell readlink -f .)

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start ./CMakeFiles ./CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start ./CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named LEDAnimationtool

# Build rule for target.
LEDAnimationtool: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 LEDAnimationtool
.PHONY : LEDAnimationtool

# fast build rule for target.
LEDAnimationtool/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LEDAnimationtool.dir/build.make CMakeFiles/LEDAnimationtool.dir/build
.PHONY : LEDAnimationtool/fast

#=============================================================================
# Target rules for targets named ws2811

# Build rule for target.
ws2811: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ws2811
.PHONY : ws2811

# fast build rule for target.
ws2811/fast:
	$(MAKE) $(MAKESILENT) -f rpi_ws281x/CMakeFiles/ws2811.dir/build.make rpi_ws281x/CMakeFiles/ws2811.dir/build
.PHONY : ws2811/fast

src/Color.o: src/Color.cpp.o
.PHONY : src/Color.o

# target to build an object file
src/Color.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LEDAnimationtool.dir/build.make CMakeFiles/LEDAnimationtool.dir/src/Color.cpp.o
.PHONY : src/Color.cpp.o

src/Color.i: src/Color.cpp.i
.PHONY : src/Color.i

# target to preprocess a source file
src/Color.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LEDAnimationtool.dir/build.make CMakeFiles/LEDAnimationtool.dir/src/Color.cpp.i
.PHONY : src/Color.cpp.i

src/Color.s: src/Color.cpp.s
.PHONY : src/Color.s

# target to generate assembly for a file
src/Color.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LEDAnimationtool.dir/build.make CMakeFiles/LEDAnimationtool.dir/src/Color.cpp.s
.PHONY : src/Color.cpp.s

src/ColorSequence.o: src/ColorSequence.cpp.o
.PHONY : src/ColorSequence.o

# target to build an object file
src/ColorSequence.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LEDAnimationtool.dir/build.make CMakeFiles/LEDAnimationtool.dir/src/ColorSequence.cpp.o
.PHONY : src/ColorSequence.cpp.o

src/ColorSequence.i: src/ColorSequence.cpp.i
.PHONY : src/ColorSequence.i

# target to preprocess a source file
src/ColorSequence.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LEDAnimationtool.dir/build.make CMakeFiles/LEDAnimationtool.dir/src/ColorSequence.cpp.i
.PHONY : src/ColorSequence.cpp.i

src/ColorSequence.s: src/ColorSequence.cpp.s
.PHONY : src/ColorSequence.s

# target to generate assembly for a file
src/ColorSequence.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LEDAnimationtool.dir/build.make CMakeFiles/LEDAnimationtool.dir/src/ColorSequence.cpp.s
.PHONY : src/ColorSequence.cpp.s

src/FrequencyColors.o: src/FrequencyColors.cpp.o
.PHONY : src/FrequencyColors.o

# target to build an object file
src/FrequencyColors.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LEDAnimationtool.dir/build.make CMakeFiles/LEDAnimationtool.dir/src/FrequencyColors.cpp.o
.PHONY : src/FrequencyColors.cpp.o

src/FrequencyColors.i: src/FrequencyColors.cpp.i
.PHONY : src/FrequencyColors.i

# target to preprocess a source file
src/FrequencyColors.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LEDAnimationtool.dir/build.make CMakeFiles/LEDAnimationtool.dir/src/FrequencyColors.cpp.i
.PHONY : src/FrequencyColors.cpp.i

src/FrequencyColors.s: src/FrequencyColors.cpp.s
.PHONY : src/FrequencyColors.s

# target to generate assembly for a file
src/FrequencyColors.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LEDAnimationtool.dir/build.make CMakeFiles/LEDAnimationtool.dir/src/FrequencyColors.cpp.s
.PHONY : src/FrequencyColors.cpp.s

src/Scene.o: src/Scene.cpp.o
.PHONY : src/Scene.o

# target to build an object file
src/Scene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LEDAnimationtool.dir/build.make CMakeFiles/LEDAnimationtool.dir/src/Scene.cpp.o
.PHONY : src/Scene.cpp.o

src/Scene.i: src/Scene.cpp.i
.PHONY : src/Scene.i

# target to preprocess a source file
src/Scene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LEDAnimationtool.dir/build.make CMakeFiles/LEDAnimationtool.dir/src/Scene.cpp.i
.PHONY : src/Scene.cpp.i

src/Scene.s: src/Scene.cpp.s
.PHONY : src/Scene.s

# target to generate assembly for a file
src/Scene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LEDAnimationtool.dir/build.make CMakeFiles/LEDAnimationtool.dir/src/Scene.cpp.s
.PHONY : src/Scene.cpp.s

src/Section.o: src/Section.cpp.o
.PHONY : src/Section.o

# target to build an object file
src/Section.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LEDAnimationtool.dir/build.make CMakeFiles/LEDAnimationtool.dir/src/Section.cpp.o
.PHONY : src/Section.cpp.o

src/Section.i: src/Section.cpp.i
.PHONY : src/Section.i

# target to preprocess a source file
src/Section.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LEDAnimationtool.dir/build.make CMakeFiles/LEDAnimationtool.dir/src/Section.cpp.i
.PHONY : src/Section.cpp.i

src/Section.s: src/Section.cpp.s
.PHONY : src/Section.s

# target to generate assembly for a file
src/Section.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LEDAnimationtool.dir/build.make CMakeFiles/LEDAnimationtool.dir/src/Section.cpp.s
.PHONY : src/Section.cpp.s

src/Strip.o: src/Strip.cpp.o
.PHONY : src/Strip.o

# target to build an object file
src/Strip.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LEDAnimationtool.dir/build.make CMakeFiles/LEDAnimationtool.dir/src/Strip.cpp.o
.PHONY : src/Strip.cpp.o

src/Strip.i: src/Strip.cpp.i
.PHONY : src/Strip.i

# target to preprocess a source file
src/Strip.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LEDAnimationtool.dir/build.make CMakeFiles/LEDAnimationtool.dir/src/Strip.cpp.i
.PHONY : src/Strip.cpp.i

src/Strip.s: src/Strip.cpp.s
.PHONY : src/Strip.s

# target to generate assembly for a file
src/Strip.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LEDAnimationtool.dir/build.make CMakeFiles/LEDAnimationtool.dir/src/Strip.cpp.s
.PHONY : src/Strip.cpp.s

src/animation/Animation.o: src/animation/Animation.cpp.o
.PHONY : src/animation/Animation.o

# target to build an object file
src/animation/Animation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LEDAnimationtool.dir/build.make CMakeFiles/LEDAnimationtool.dir/src/animation/Animation.cpp.o
.PHONY : src/animation/Animation.cpp.o

src/animation/Animation.i: src/animation/Animation.cpp.i
.PHONY : src/animation/Animation.i

# target to preprocess a source file
src/animation/Animation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LEDAnimationtool.dir/build.make CMakeFiles/LEDAnimationtool.dir/src/animation/Animation.cpp.i
.PHONY : src/animation/Animation.cpp.i

src/animation/Animation.s: src/animation/Animation.cpp.s
.PHONY : src/animation/Animation.s

# target to generate assembly for a file
src/animation/Animation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LEDAnimationtool.dir/build.make CMakeFiles/LEDAnimationtool.dir/src/animation/Animation.cpp.s
.PHONY : src/animation/Animation.cpp.s

src/animation/Strobe.o: src/animation/Strobe.cpp.o
.PHONY : src/animation/Strobe.o

# target to build an object file
src/animation/Strobe.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LEDAnimationtool.dir/build.make CMakeFiles/LEDAnimationtool.dir/src/animation/Strobe.cpp.o
.PHONY : src/animation/Strobe.cpp.o

src/animation/Strobe.i: src/animation/Strobe.cpp.i
.PHONY : src/animation/Strobe.i

# target to preprocess a source file
src/animation/Strobe.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LEDAnimationtool.dir/build.make CMakeFiles/LEDAnimationtool.dir/src/animation/Strobe.cpp.i
.PHONY : src/animation/Strobe.cpp.i

src/animation/Strobe.s: src/animation/Strobe.cpp.s
.PHONY : src/animation/Strobe.s

# target to generate assembly for a file
src/animation/Strobe.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LEDAnimationtool.dir/build.make CMakeFiles/LEDAnimationtool.dir/src/animation/Strobe.cpp.s
.PHONY : src/animation/Strobe.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LEDAnimationtool.dir/build.make CMakeFiles/LEDAnimationtool.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LEDAnimationtool.dir/build.make CMakeFiles/LEDAnimationtool.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LEDAnimationtool.dir/build.make CMakeFiles/LEDAnimationtool.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/util/configuration/AnimationData.o: src/util/configuration/AnimationData.cpp.o
.PHONY : src/util/configuration/AnimationData.o

# target to build an object file
src/util/configuration/AnimationData.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LEDAnimationtool.dir/build.make CMakeFiles/LEDAnimationtool.dir/src/util/configuration/AnimationData.cpp.o
.PHONY : src/util/configuration/AnimationData.cpp.o

src/util/configuration/AnimationData.i: src/util/configuration/AnimationData.cpp.i
.PHONY : src/util/configuration/AnimationData.i

# target to preprocess a source file
src/util/configuration/AnimationData.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LEDAnimationtool.dir/build.make CMakeFiles/LEDAnimationtool.dir/src/util/configuration/AnimationData.cpp.i
.PHONY : src/util/configuration/AnimationData.cpp.i

src/util/configuration/AnimationData.s: src/util/configuration/AnimationData.cpp.s
.PHONY : src/util/configuration/AnimationData.s

# target to generate assembly for a file
src/util/configuration/AnimationData.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LEDAnimationtool.dir/build.make CMakeFiles/LEDAnimationtool.dir/src/util/configuration/AnimationData.cpp.s
.PHONY : src/util/configuration/AnimationData.cpp.s

src/util/database/AnimationDB.o: src/util/database/AnimationDB.cpp.o
.PHONY : src/util/database/AnimationDB.o

# target to build an object file
src/util/database/AnimationDB.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LEDAnimationtool.dir/build.make CMakeFiles/LEDAnimationtool.dir/src/util/database/AnimationDB.cpp.o
.PHONY : src/util/database/AnimationDB.cpp.o

src/util/database/AnimationDB.i: src/util/database/AnimationDB.cpp.i
.PHONY : src/util/database/AnimationDB.i

# target to preprocess a source file
src/util/database/AnimationDB.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LEDAnimationtool.dir/build.make CMakeFiles/LEDAnimationtool.dir/src/util/database/AnimationDB.cpp.i
.PHONY : src/util/database/AnimationDB.cpp.i

src/util/database/AnimationDB.s: src/util/database/AnimationDB.cpp.s
.PHONY : src/util/database/AnimationDB.s

# target to generate assembly for a file
src/util/database/AnimationDB.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LEDAnimationtool.dir/build.make CMakeFiles/LEDAnimationtool.dir/src/util/database/AnimationDB.cpp.s
.PHONY : src/util/database/AnimationDB.cpp.s

src/util/database/ColorDB.o: src/util/database/ColorDB.cpp.o
.PHONY : src/util/database/ColorDB.o

# target to build an object file
src/util/database/ColorDB.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LEDAnimationtool.dir/build.make CMakeFiles/LEDAnimationtool.dir/src/util/database/ColorDB.cpp.o
.PHONY : src/util/database/ColorDB.cpp.o

src/util/database/ColorDB.i: src/util/database/ColorDB.cpp.i
.PHONY : src/util/database/ColorDB.i

# target to preprocess a source file
src/util/database/ColorDB.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LEDAnimationtool.dir/build.make CMakeFiles/LEDAnimationtool.dir/src/util/database/ColorDB.cpp.i
.PHONY : src/util/database/ColorDB.cpp.i

src/util/database/ColorDB.s: src/util/database/ColorDB.cpp.s
.PHONY : src/util/database/ColorDB.s

# target to generate assembly for a file
src/util/database/ColorDB.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LEDAnimationtool.dir/build.make CMakeFiles/LEDAnimationtool.dir/src/util/database/ColorDB.cpp.s
.PHONY : src/util/database/ColorDB.cpp.s

src/util/database/ColorSequenceDB.o: src/util/database/ColorSequenceDB.cpp.o
.PHONY : src/util/database/ColorSequenceDB.o

# target to build an object file
src/util/database/ColorSequenceDB.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LEDAnimationtool.dir/build.make CMakeFiles/LEDAnimationtool.dir/src/util/database/ColorSequenceDB.cpp.o
.PHONY : src/util/database/ColorSequenceDB.cpp.o

src/util/database/ColorSequenceDB.i: src/util/database/ColorSequenceDB.cpp.i
.PHONY : src/util/database/ColorSequenceDB.i

# target to preprocess a source file
src/util/database/ColorSequenceDB.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LEDAnimationtool.dir/build.make CMakeFiles/LEDAnimationtool.dir/src/util/database/ColorSequenceDB.cpp.i
.PHONY : src/util/database/ColorSequenceDB.cpp.i

src/util/database/ColorSequenceDB.s: src/util/database/ColorSequenceDB.cpp.s
.PHONY : src/util/database/ColorSequenceDB.s

# target to generate assembly for a file
src/util/database/ColorSequenceDB.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LEDAnimationtool.dir/build.make CMakeFiles/LEDAnimationtool.dir/src/util/database/ColorSequenceDB.cpp.s
.PHONY : src/util/database/ColorSequenceDB.cpp.s

src/util/database/Database.o: src/util/database/Database.cpp.o
.PHONY : src/util/database/Database.o

# target to build an object file
src/util/database/Database.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LEDAnimationtool.dir/build.make CMakeFiles/LEDAnimationtool.dir/src/util/database/Database.cpp.o
.PHONY : src/util/database/Database.cpp.o

src/util/database/Database.i: src/util/database/Database.cpp.i
.PHONY : src/util/database/Database.i

# target to preprocess a source file
src/util/database/Database.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LEDAnimationtool.dir/build.make CMakeFiles/LEDAnimationtool.dir/src/util/database/Database.cpp.i
.PHONY : src/util/database/Database.cpp.i

src/util/database/Database.s: src/util/database/Database.cpp.s
.PHONY : src/util/database/Database.s

# target to generate assembly for a file
src/util/database/Database.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LEDAnimationtool.dir/build.make CMakeFiles/LEDAnimationtool.dir/src/util/database/Database.cpp.s
.PHONY : src/util/database/Database.cpp.s

src/util/database/DetectionDB.o: src/util/database/DetectionDB.cpp.o
.PHONY : src/util/database/DetectionDB.o

# target to build an object file
src/util/database/DetectionDB.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LEDAnimationtool.dir/build.make CMakeFiles/LEDAnimationtool.dir/src/util/database/DetectionDB.cpp.o
.PHONY : src/util/database/DetectionDB.cpp.o

src/util/database/DetectionDB.i: src/util/database/DetectionDB.cpp.i
.PHONY : src/util/database/DetectionDB.i

# target to preprocess a source file
src/util/database/DetectionDB.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LEDAnimationtool.dir/build.make CMakeFiles/LEDAnimationtool.dir/src/util/database/DetectionDB.cpp.i
.PHONY : src/util/database/DetectionDB.cpp.i

src/util/database/DetectionDB.s: src/util/database/DetectionDB.cpp.s
.PHONY : src/util/database/DetectionDB.s

# target to generate assembly for a file
src/util/database/DetectionDB.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LEDAnimationtool.dir/build.make CMakeFiles/LEDAnimationtool.dir/src/util/database/DetectionDB.cpp.s
.PHONY : src/util/database/DetectionDB.cpp.s

src/util/database/FrequencyColorDB.o: src/util/database/FrequencyColorDB.cpp.o
.PHONY : src/util/database/FrequencyColorDB.o

# target to build an object file
src/util/database/FrequencyColorDB.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LEDAnimationtool.dir/build.make CMakeFiles/LEDAnimationtool.dir/src/util/database/FrequencyColorDB.cpp.o
.PHONY : src/util/database/FrequencyColorDB.cpp.o

src/util/database/FrequencyColorDB.i: src/util/database/FrequencyColorDB.cpp.i
.PHONY : src/util/database/FrequencyColorDB.i

# target to preprocess a source file
src/util/database/FrequencyColorDB.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LEDAnimationtool.dir/build.make CMakeFiles/LEDAnimationtool.dir/src/util/database/FrequencyColorDB.cpp.i
.PHONY : src/util/database/FrequencyColorDB.cpp.i

src/util/database/FrequencyColorDB.s: src/util/database/FrequencyColorDB.cpp.s
.PHONY : src/util/database/FrequencyColorDB.s

# target to generate assembly for a file
src/util/database/FrequencyColorDB.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LEDAnimationtool.dir/build.make CMakeFiles/LEDAnimationtool.dir/src/util/database/FrequencyColorDB.cpp.s
.PHONY : src/util/database/FrequencyColorDB.cpp.s

src/util/database/InitializeDB.o: src/util/database/InitializeDB.cpp.o
.PHONY : src/util/database/InitializeDB.o

# target to build an object file
src/util/database/InitializeDB.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LEDAnimationtool.dir/build.make CMakeFiles/LEDAnimationtool.dir/src/util/database/InitializeDB.cpp.o
.PHONY : src/util/database/InitializeDB.cpp.o

src/util/database/InitializeDB.i: src/util/database/InitializeDB.cpp.i
.PHONY : src/util/database/InitializeDB.i

# target to preprocess a source file
src/util/database/InitializeDB.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LEDAnimationtool.dir/build.make CMakeFiles/LEDAnimationtool.dir/src/util/database/InitializeDB.cpp.i
.PHONY : src/util/database/InitializeDB.cpp.i

src/util/database/InitializeDB.s: src/util/database/InitializeDB.cpp.s
.PHONY : src/util/database/InitializeDB.s

# target to generate assembly for a file
src/util/database/InitializeDB.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LEDAnimationtool.dir/build.make CMakeFiles/LEDAnimationtool.dir/src/util/database/InitializeDB.cpp.s
.PHONY : src/util/database/InitializeDB.cpp.s

src/util/database/SceneAnimationDB.o: src/util/database/SceneAnimationDB.cpp.o
.PHONY : src/util/database/SceneAnimationDB.o

# target to build an object file
src/util/database/SceneAnimationDB.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LEDAnimationtool.dir/build.make CMakeFiles/LEDAnimationtool.dir/src/util/database/SceneAnimationDB.cpp.o
.PHONY : src/util/database/SceneAnimationDB.cpp.o

src/util/database/SceneAnimationDB.i: src/util/database/SceneAnimationDB.cpp.i
.PHONY : src/util/database/SceneAnimationDB.i

# target to preprocess a source file
src/util/database/SceneAnimationDB.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LEDAnimationtool.dir/build.make CMakeFiles/LEDAnimationtool.dir/src/util/database/SceneAnimationDB.cpp.i
.PHONY : src/util/database/SceneAnimationDB.cpp.i

src/util/database/SceneAnimationDB.s: src/util/database/SceneAnimationDB.cpp.s
.PHONY : src/util/database/SceneAnimationDB.s

# target to generate assembly for a file
src/util/database/SceneAnimationDB.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LEDAnimationtool.dir/build.make CMakeFiles/LEDAnimationtool.dir/src/util/database/SceneAnimationDB.cpp.s
.PHONY : src/util/database/SceneAnimationDB.cpp.s

src/util/database/SceneDB.o: src/util/database/SceneDB.cpp.o
.PHONY : src/util/database/SceneDB.o

# target to build an object file
src/util/database/SceneDB.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LEDAnimationtool.dir/build.make CMakeFiles/LEDAnimationtool.dir/src/util/database/SceneDB.cpp.o
.PHONY : src/util/database/SceneDB.cpp.o

src/util/database/SceneDB.i: src/util/database/SceneDB.cpp.i
.PHONY : src/util/database/SceneDB.i

# target to preprocess a source file
src/util/database/SceneDB.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LEDAnimationtool.dir/build.make CMakeFiles/LEDAnimationtool.dir/src/util/database/SceneDB.cpp.i
.PHONY : src/util/database/SceneDB.cpp.i

src/util/database/SceneDB.s: src/util/database/SceneDB.cpp.s
.PHONY : src/util/database/SceneDB.s

# target to generate assembly for a file
src/util/database/SceneDB.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LEDAnimationtool.dir/build.make CMakeFiles/LEDAnimationtool.dir/src/util/database/SceneDB.cpp.s
.PHONY : src/util/database/SceneDB.cpp.s

src/util/database/SectionAnimationDB.o: src/util/database/SectionAnimationDB.cpp.o
.PHONY : src/util/database/SectionAnimationDB.o

# target to build an object file
src/util/database/SectionAnimationDB.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LEDAnimationtool.dir/build.make CMakeFiles/LEDAnimationtool.dir/src/util/database/SectionAnimationDB.cpp.o
.PHONY : src/util/database/SectionAnimationDB.cpp.o

src/util/database/SectionAnimationDB.i: src/util/database/SectionAnimationDB.cpp.i
.PHONY : src/util/database/SectionAnimationDB.i

# target to preprocess a source file
src/util/database/SectionAnimationDB.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LEDAnimationtool.dir/build.make CMakeFiles/LEDAnimationtool.dir/src/util/database/SectionAnimationDB.cpp.i
.PHONY : src/util/database/SectionAnimationDB.cpp.i

src/util/database/SectionAnimationDB.s: src/util/database/SectionAnimationDB.cpp.s
.PHONY : src/util/database/SectionAnimationDB.s

# target to generate assembly for a file
src/util/database/SectionAnimationDB.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LEDAnimationtool.dir/build.make CMakeFiles/LEDAnimationtool.dir/src/util/database/SectionAnimationDB.cpp.s
.PHONY : src/util/database/SectionAnimationDB.cpp.s

src/util/database/SectionDB.o: src/util/database/SectionDB.cpp.o
.PHONY : src/util/database/SectionDB.o

# target to build an object file
src/util/database/SectionDB.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LEDAnimationtool.dir/build.make CMakeFiles/LEDAnimationtool.dir/src/util/database/SectionDB.cpp.o
.PHONY : src/util/database/SectionDB.cpp.o

src/util/database/SectionDB.i: src/util/database/SectionDB.cpp.i
.PHONY : src/util/database/SectionDB.i

# target to preprocess a source file
src/util/database/SectionDB.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LEDAnimationtool.dir/build.make CMakeFiles/LEDAnimationtool.dir/src/util/database/SectionDB.cpp.i
.PHONY : src/util/database/SectionDB.cpp.i

src/util/database/SectionDB.s: src/util/database/SectionDB.cpp.s
.PHONY : src/util/database/SectionDB.s

# target to generate assembly for a file
src/util/database/SectionDB.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LEDAnimationtool.dir/build.make CMakeFiles/LEDAnimationtool.dir/src/util/database/SectionDB.cpp.s
.PHONY : src/util/database/SectionDB.cpp.s

src/util/udp/UDP.o: src/util/udp/UDP.cpp.o
.PHONY : src/util/udp/UDP.o

# target to build an object file
src/util/udp/UDP.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LEDAnimationtool.dir/build.make CMakeFiles/LEDAnimationtool.dir/src/util/udp/UDP.cpp.o
.PHONY : src/util/udp/UDP.cpp.o

src/util/udp/UDP.i: src/util/udp/UDP.cpp.i
.PHONY : src/util/udp/UDP.i

# target to preprocess a source file
src/util/udp/UDP.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LEDAnimationtool.dir/build.make CMakeFiles/LEDAnimationtool.dir/src/util/udp/UDP.cpp.i
.PHONY : src/util/udp/UDP.cpp.i

src/util/udp/UDP.s: src/util/udp/UDP.cpp.s
.PHONY : src/util/udp/UDP.s

# target to generate assembly for a file
src/util/udp/UDP.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/LEDAnimationtool.dir/build.make CMakeFiles/LEDAnimationtool.dir/src/util/udp/UDP.cpp.s
.PHONY : src/util/udp/UDP.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... LEDAnimationtool"
	@echo "... ws2811"
	@echo "... src/Color.o"
	@echo "... src/Color.i"
	@echo "... src/Color.s"
	@echo "... src/ColorSequence.o"
	@echo "... src/ColorSequence.i"
	@echo "... src/ColorSequence.s"
	@echo "... src/FrequencyColors.o"
	@echo "... src/FrequencyColors.i"
	@echo "... src/FrequencyColors.s"
	@echo "... src/Scene.o"
	@echo "... src/Scene.i"
	@echo "... src/Scene.s"
	@echo "... src/Section.o"
	@echo "... src/Section.i"
	@echo "... src/Section.s"
	@echo "... src/Strip.o"
	@echo "... src/Strip.i"
	@echo "... src/Strip.s"
	@echo "... src/animation/Animation.o"
	@echo "... src/animation/Animation.i"
	@echo "... src/animation/Animation.s"
	@echo "... src/animation/Strobe.o"
	@echo "... src/animation/Strobe.i"
	@echo "... src/animation/Strobe.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/util/configuration/AnimationData.o"
	@echo "... src/util/configuration/AnimationData.i"
	@echo "... src/util/configuration/AnimationData.s"
	@echo "... src/util/database/AnimationDB.o"
	@echo "... src/util/database/AnimationDB.i"
	@echo "... src/util/database/AnimationDB.s"
	@echo "... src/util/database/ColorDB.o"
	@echo "... src/util/database/ColorDB.i"
	@echo "... src/util/database/ColorDB.s"
	@echo "... src/util/database/ColorSequenceDB.o"
	@echo "... src/util/database/ColorSequenceDB.i"
	@echo "... src/util/database/ColorSequenceDB.s"
	@echo "... src/util/database/Database.o"
	@echo "... src/util/database/Database.i"
	@echo "... src/util/database/Database.s"
	@echo "... src/util/database/DetectionDB.o"
	@echo "... src/util/database/DetectionDB.i"
	@echo "... src/util/database/DetectionDB.s"
	@echo "... src/util/database/FrequencyColorDB.o"
	@echo "... src/util/database/FrequencyColorDB.i"
	@echo "... src/util/database/FrequencyColorDB.s"
	@echo "... src/util/database/InitializeDB.o"
	@echo "... src/util/database/InitializeDB.i"
	@echo "... src/util/database/InitializeDB.s"
	@echo "... src/util/database/SceneAnimationDB.o"
	@echo "... src/util/database/SceneAnimationDB.i"
	@echo "... src/util/database/SceneAnimationDB.s"
	@echo "... src/util/database/SceneDB.o"
	@echo "... src/util/database/SceneDB.i"
	@echo "... src/util/database/SceneDB.s"
	@echo "... src/util/database/SectionAnimationDB.o"
	@echo "... src/util/database/SectionAnimationDB.i"
	@echo "... src/util/database/SectionAnimationDB.s"
	@echo "... src/util/database/SectionDB.o"
	@echo "... src/util/database/SectionDB.i"
	@echo "... src/util/database/SectionDB.s"
	@echo "... src/util/udp/UDP.o"
	@echo "... src/util/udp/UDP.i"
	@echo "... src/util/udp/UDP.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

